trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- scipt: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'